---
fixtures:
  repositories:
    haveged:
      repo: https://github.com/simp/puppet-haveged
      branch: simp-master
    iptables: https://github.com/simp/pupmod-simp-iptables
    simplib: https://github.com/simp/pupmod-simp-simplib
    simp_options: https://github.com/simp/pupmod-simp-simp_options
    stdlib:
      repo: https://github.com/simp/puppetlabs-stdlib
      branch: master
  symlinks:
    krb5: "#{source_dir}"
